### PR TITLE
chore(codequality): java templates and intelliJ settings.

### PR DESCRIPTION
**Pull request by fclement-yseop**
The first aim of the Pull Request is to document the configuration of a code formatter in IntelliJ. To check that the code formaters have the same behaviour in Eclipse and IntelliJ, a few example java files are given. Developers can now run their formatter on these files to check that it's well configured.
These files examples were written from Eclipse code formatter examples. They're probably not exhaustive and may be enriched in the future.

### CODE REVIEW

**Comment by eborel-yseop** [comment]
I don't get why we need a plugin to use the existing eclipse formatter ? IntelliJ supports them natively.

**Comment by fclement-yseop** [comment]
IntelliJ can *import* an Eclipse code formatter, but it only use it to initialize its own settings. And when checking, I saw quite annoying differences between both formatters that I noted in the README:
>>>
Tries to configure the IntelliJ standard code formatter to match the Eclipse code formatter settings weren't successfull: there were always differences between both formatters (especially in Javadoc, empty blocks and white lines).

**Comment by fclement-yseop** [comment]
I'd have preferred to use the IJ standard code formatter, but if we have projects with some developers on IJ and some on Eclipse, I thought it'll be better to guaranty the same formatting results in both IDEs.

**Comment by eborel-yseop** [comment]
Mmm ok then, that'll do for now :)

**Pull request merged**
